'use strict';

// ─── AI ANALYSIS CONFIG ───────────────────────────────────────────────────────
// Edit this file to change the analysis prompt or add/remove AI targets.

const AI_CONFIG = {

  // ── Targets ─────────────────────────────────────────────────────────────────
  targets: [
    {
      id:     'claude',
      label:  'Claude',
      url:    'https://claude.ai/new',
      appUrl: 'claude://',
      img:    'claude-logo.svg',
      bg:     '#F3E5F5',
      fg:     '#6A1B9A'
    },
    {
      id:     'chatgpt',
      label:  'ChatGPT',
      url:    'https://chatgpt.com/',
      appUrl: 'chatgpt://',
      img:    'openai-logo.svg',
      bg:     '#E8F5E9',
      fg:     '#1B5E20'
    }
  ],

  // ── Prompt template ──────────────────────────────────────────────────────────
  // Receives the match payload object and returns the full prompt string.
  buildPrompt(payload) {
    return `You are an expert GAA (Gaelic Athletic Association) match analyst and coaching assistant. \
Analyse the match tracking data below and write a coaching report that will be saved as a permanent \
match record. The report should read as flowing, connected prose — not bullet points or numbered lists. \
Write it as an experienced analyst would brief a head coach: clear, direct, and grounded in the data.

GAELIC GAMES CONTEXT:
- Goal = 3 points (ball into the net under the crossbar)
- Point = 1 point (ball over the crossbar between the posts)
- Score notation: Goals-Points (total in brackets), e.g. 2-14 (20pts)
- Sports: Football and Hurling. Hurling uses a hurley and sliotar.
- Kickout (football) / Puck-out (hurling): restart after a score or wide, taken by the goalkeeper.
- Turnover Won: our team regains possession. Turnover Lost: opposition regains possession.
- Free: a foul by our team conceding a free kick/puck to the opposition.

COVER THE FOLLOWING IN YOUR REPORT — in natural prose with short paragraph headings only:

Overall Performance
A concise opening summary of the result and the general shape of the performance.

Scoring & Efficiency
How the team scored, conversion rate, wide rate, placed ball performance, and how scoring
was distributed across both halves and among players.

Possession & Turnovers
The turnover won/lost balance, who drove it, whether turnovers clustered at particular
times, and what they tell us about how the team managed possession under pressure.

Restarts
Own and opposition kickout/puck-out retention, whether either team gained a meaningful
advantage from restarts, and any clear patterns in how they were used.

Discipline
Frees conceded, cards, and the direct scoring cost of disciplinary lapses. Name players
where relevant and note any positional or temporal patterns.

Substitutions & Impact
When changes were made, the score at the time, and whether the subs visibly shifted momentum.

Key Individuals
Standout performances — both positive and where improvement is needed. Be honest and specific.

Hidden Patterns
This is the most important section. Analyse the raw event sequence for non-obvious patterns \
a sideline observer would miss. Specifically look for:
chained turnovers (a won turnover quickly followed by a lost one, or vice versa, suggesting \
an inability to capitalise); restart-triggered scoring runs (repeated sequences where won or \
lost restarts directly precede scores); free clustering (the same player, phase, or game \
period producing repeated fouls); score drought triggers (what events consistently appear \
just before the team stops scoring); and momentum cascades (a single negative event — wide, \
lost turnover, free conceded — that appears to set off a chain of further negative events \
in a short window). Call out each pattern by name, note how often it occurred, and explain \
why it matters for preparation.

Coaching Priorities
Close with three specific, actionable things to address at the next training session. \
Write them as clear directives, not observations.

NAMING & TIMING STYLE:
Refer to players by their full name on first mention, then by First Initial. Surname \
(e.g. "Ciarán Kearney" becomes "C. Kearney") for all subsequent references. Express \
times as "the 12th minute" or "early/late in the first/second half" rather than quoting \
raw timestamps. Where several events of the same type occur in quick succession, describe \
them as a cluster in a single sentence rather than listing each one individually.

Ground every observation in actual sequences from the event log. Keep the tone \
professional but direct — this report will be read by coaches, not statisticians.

End the report with the following disclaimer, reproduced exactly and in full:

---
Data & AI Notice: This analysis was generated by an AI model based on match data captured \
manually by a sideline operator during live play. Reactive, real-time data collection of \
this kind is subject to human factors including missed events, timing inaccuracies, \
misattributed actions, and incomplete sequences — particularly during periods of high \
intensity or congestion. Observations and patterns identified in this report should be \
treated as analytical prompts for discussion rather than definitive conclusions. Coaches \
are encouraged to cross-reference with video footage and their own match observations \
before acting on any finding. This report was produced by an AI assistant and does not \
constitute professional coaching advice.
---

---
FIXTURE:
${payload.fixture}

FINAL SCORE:
${payload.result}

SQUAD (position number → player name):
${payload.squad}

EVENT LOG (time  player  action  sub-type):
${payload.eventLog}
`;
  },

  // ── Event log formatter ───────────────────────────────────────────────────────
  // Converts raw events into a human-readable line per event.
  buildEventLog(state) {
    const pnames = state.pnames || {};
    const slotp  = state.slotp  || {};
    const fullName = pi => (pnames[pi] || '').trim() || `#${pi}`;
    const playerOf = ev => {
      const pi = ev.pi != null ? ev.pi : (ev.slot != null ? slotp[ev.slot] : null);
      return pi != null ? fullName(pi) : null;
    };

    return (state.evts || []).map(ev => {
      const t = ev.time || '??:??';
      if (ev.badge === '1H')  return `${t}  ───  HALF TIME`;
      if (ev.badge === '2H')  return `${t}  ───  SECOND HALF BEGINS`;
      if (ev.badge === 'END') return `${t}  ───  FULL TIME`;
      if (ev.badge === 'OPP') return `${t}  Opposition        ${ev.desc || ''}`;
      if (ev.badge === 'ADJ') return `${t}  Score adjustment  ${ev.desc || ''}`;
      if (ev.badge === 'RSTR') return `${t}  Restart           ${ev.desc || ''}`;
      const player = (playerOf(ev) || '—').padEnd(22);
      const action = ev.action || ev.badge || '?';
      const sub    = ev.sec ? ` (${ev.sec})` : '';
      const extra  = ev.action === 'sub' ? `  ${ev.desc || ''}` : '';
      return `${t}  ${player}  ${action}${sub}${extra}`;
    }).join('\n');
  },

  // ── Payload builder ──────────────────────────────────────────────────────────
  // Extracts the relevant match data from state to keep the prompt focused.
  buildPayload(state) {
    const squadLines = Object.entries(state.slotp || {})
      .sort(([a], [b]) => +a - +b)
      .map(([slot, pi]) => `  #${slot}: ${(state.pnames && state.pnames[pi]) || `#${pi}`}`)
      .join('\n');

    const fixture = [
      `  Teams:       ${state.usN || '?'} vs ${state.oppN || '?'}`,
      `  Sport:       ${state.sport || 'football'}`,
      state.competition ? `  Competition: ${state.competition}` : null,
      state.location    ? `  Location:    ${state.location}`    : null,
      state.matchDate   ? `  Date:        ${state.matchDate}`   : null,
      state.ageGrade    ? `  Age grade:   ${state.ageGrade}`    : null,
    ].filter(Boolean).join('\n');

    return {
      fixture,
      result:   `  ${state.usN || 'Us'}: ${state.goals}-${state.pts} (${state.goals * 3 + state.pts}pts)` +
                `\n  ${state.oppN || 'Opposition'}: ${state.og}-${state.op_} (${state.og * 3 + state.op_}pts)`,
      squad:    squadLines,
      eventLog: this.buildEventLog(state)
    };
  }

};
